Add support for EventRateLimit admission plugin
kubermatic/dashboard pull request #3948
Opened 2021-12-13 08:46 UTC by ahmedwaleedmalik

### What this PR does / why we need it
Add support for admission plugin `EventRateLimit`. Right now the only allowed limit type is `Namespace` for the plugin. 

### Which issue(s) this PR fixes

Fixes https://github.com/kubermatic/edgematic/issues/77

### Special notes for your reviewer

### Release note

```release-note
Support for EventRateLimit admission plugin
```

2021-12-13 08:59 UTC, floreks commented
I think we need some input from @cschieder about the design improvements. It doesn't match our current styling.

2021-12-14 07:29 UTC, ahmedwaleedmalik commented
/retest

2021-12-14 15:18 UTC, ahmedwaleedmalik commented
/retest

2021-12-15 09:40 UTC, cschieder commented
New feedback after talking with @floreks, he had some good points

- Change it to "Namespace Event Rate Limit" in the dropdown and "Namespace Event Rate Limit Configuration" in the headline
- Add a description what this is and what it does to the info icon tooltip

2021-12-15 10:06 UTC, floreks requested changes
Few additional remarks from my side

2021-12-15 10:06 UTC, floreks commented on src/app/shared/components/event-rate-limit/style.scss
> +  display: flex;
Same as before. Most of the time whole flex layout can be controlled by using `fxFlex`.

2021-12-15 10:06 UTC, floreks commented on src/app/shared/components/number-stepper/style.scss
> +  min-width: 130px;
Do not change this globally as it will update our whole UI and many other places. You can create a custom class that when applied changes the width.

2021-12-15 10:06 UTC, floreks commented on src/app/shared/components/event-rate-limit/template.html
> +                       label="CacheSize"
s/CacheSize/Cache Size

2021-12-15 10:08 UTC, floreks commented
One more thing. Making the stepper width smaller makes the error overlap below text.

![image](https://user-images.githubusercontent.com/2285385/146166820-acf2e559-2ba5-4f56-818a-5830a66fd197.png)

2021-12-15 14:48 UTC, cschieder commented
Are there some recommended values we can set there by default instead of just setting 1? Also we can change the error message to "Minimum value is 1" not sure if the "acceptable" is needed

2021-12-16 07:47 UTC, ahmedwaleedmalik commented
Most of the feedback is handled. The following is left at the moment:

> Making the stepper width smaller makes the error overlap the below text.

Yes, that is an issue that needs to be fixed. I reverted it to the old value of `min-width` but the issue still persists. I really don't want to opt for one input per line for this numeric input though.

> Change it to "Namespace Event Rate Limit" in the dropdown 

That's probably why I resorted to adding a `disabled` drop-down to show the limit type i.e. namespace. @floreks I'll have to add a special case [here](https://github.com/ahmedwaleedmalik/dashboard/blob/event-rate-limit-admission-plugin/src/app/shared/utils/admission-plugin-utils/admission-plugin-utils.ts#L27) for this. Are you okay with that?

2021-12-16 07:59 UTC, embik commented
> Change it to "Namespace Event Rate Limit" in the dropdown

A note on this, the API supports all types for the EventRateLimit plugin (namespace, cluster, user and source), but we decided to go a MVP route and only expose the namespace settings for now. But it's feasible to introduce more fields for it if customers/users are asking for it. I'm not sure I think renaming this is a good idea, given that the names are usually based on the admission plugin names, and this one _is_ named "EventRateLimit".

2021-12-16 09:53 UTC, floreks commented
@embik @ahmedwaleedmalik since all values are actually supported and we only block other types now, I'd vote for having the disabled combobox with preselected `Namespace` type as initially proposed. I assume that after the release we will be enabling all options and it will be much simpler for us to do this.

2021-12-16 09:53 UTC, floreks requested changes

2021-12-16 09:53 UTC, floreks commented on src/app/shared/components/cluster-summary/style.scss
> +.km-event-rate-limit {
As mentioned `km-` prefix is for the globally available styles only. Here is it a local style.

s/km-event-rate-limit/event-rate-limit

2021-12-16 09:53 UTC, floreks commented on src/app/shared/components/cluster-summary/style.scss
> +.km-event-rate-limit-values {
s/km-event-rate-limit-values/event-rate-limit-value

2021-12-16 09:53 UTC, floreks commented on src/app/shared/components/cluster-summary/style.scss
> +  display: flex;
Flex usage was also mentioned in another comment. Should be replaced with `fxFlex`.

2021-12-16 09:53 UTC, floreks commented on src/app/shared/components/event-rate-limit/style.scss
> +  margin: 0 !important;
Do not use `!important` modifier. We are trying to get rid of it at all from the codebase as it often causes conflicts and makes it hard to debug.

2021-12-16 11:59 UTC, ahmedwaleedmalik commented
Feedback handled and screenshots updated.

2021-12-17 09:51 UTC, floreks commented
/lgtm

2021-12-17 09:51 UTC, floreks commented
@cschieder any objections regarding the updated design?

2021-12-20 07:33 UTC, cschieder commented
Is there no way to put the number inputs next to each other like initially planned? @floreks

2021-12-20 08:38 UTC, floreks commented
There is always a way. The question is do we want error message to be 5 lines long due to very small width?

2021-12-20 08:49 UTC, cschieder commented
The error values that will barely happen because we pre-fill it with existing values? Also we can optimise wording and they can span the width of the + and - boxes as well

2021-12-20 08:55 UTC, floreks commented
> The error values that will barely happen because we pre-fill it with existing values? Also we can optimise wording and they can span the width of the + and - boxes as well

Even if they happen rarely they should still be clearly displayed in a readable format, without overlapping other elements like before.

We can't make them span to the full length of the component as they are handled by angular and are part of the input only. They will always match input width.

2021-12-20 11:17 UTC, floreks commented
@ahmedwaleedmalik as a result of discussion with @cschieder we'd like to get back to the single-line design.

Also, the number stepper error message can be changed

`Maximum value is ...` -> `Maximum is ...`
`Minimum values is ...` -> `Minimum is ...`
`Expected provided number to be an integer.` -> `Whole number expected`

If you need any help with updating width only for this single view let me know. I can do this.

2021-12-21 08:31 UTC, ahmedwaleedmalik commented
> If you need any help with updating width only for this single view let me know. I can do this.

@floreks I have managed the rest but the width for the form elements is still pending. Do let me know when you have a few minutes for that, I'll setup the environment at my end.

2021-12-21 11:38 UTC, floreks commented
/retest

2021-12-21 12:00 UTC, floreks commented
### Updated
![2021-12-21_12-56](https://user-images.githubusercontent.com/2285385/146926647-74b9963e-5cef-4c93-a24f-09cc3d40a2f9.png)

2021-12-21 12:04 UTC, ahmedwaleedmalik commented
@floreks thank you for taking care of this. Can you please attach a screenshot for the `edit cluster` view as well?

2021-12-21 12:10 UTC, floreks commented
@ahmedwaleedmalik I would if our dev would actually provision any cluster :joy: I tried creating multiple different clusters but they are permanently pending.

2021-12-21 13:39 UTC, floreks commented
/retest

2021-12-21 15:22 UTC, ahmedwaleedmalik commented
/retest

2021-12-22 07:15 UTC, ahmedwaleedmalik commented
/retest

Some tests for `kubevirt` are failing. Trying one more time before I try and resolve the issue since I'm expecting this to be a flake/temp issue.

2021-12-22 11:05 UTC, ahmedwaleedmalik commented
/retest

Tests for `kubevirt` are passing and the one that is failing seems like a flake; `tories/service-accounts.spec.ts > should add token`

2021-12-22 12:19 UTC, ahmedwaleedmalik commented
/retest

2021-12-22 12:27 UTC, floreks commented
/lgtm
/approve

2021-12-22 19:20 UTC, merged