Pre-select rocky linux while editing machine deployment
kubermatic/dashboard pull request #4588
Opened 2022-06-14 12:06 UTC by Talha-Jamil-TJ

Signed-off-by: Talha Jamil TJ <talha.jamil@kubermatic.com>

### What this PR does / why we need it

fixes the spelling of rocky linux from "rockylinux" to "rockyLinux" in **OperatingSystem** enum

Now while editing machine deployments **Rocky Linux** will be selected by default

<img width="673" alt="image" src="https://user-images.githubusercontent.com/56511988/173573011-ccb9fa25-ddb1-4951-9fb8-4b33b047d26f.png">

### Which issue(s) this PR fixes

Closes #4571 

### Release note

```release-note
NONE
```

2022-06-14 15:44 UTC, Waseem826 requested changes
While this works fine in Edit Machine Deployment modal but it doesn't work in Machine Deployments table. That's because we need to rename `rockylinux` property in `OperatingSystemSpec` class as well. And I think we should also rename all other occurrences of `rockylinux` with `rockyLinux` (CSS class names etc.) just to be consistent everywhere.

![screenshot-localhost_8000-2022 06 14-20_41_11](https://user-images.githubusercontent.com/13975988/173619737-acb5a6b2-90fc-44b0-9489-1a2c87538b5e.png)

2022-06-14 16:05 UTC, Talha-Jamil-TJ commented
> While this works fine in Edit Machine Deployment modal but it doesn't work in Machine Deployments table. That's because we need to rename `rockylinux` property in `OperatingSystemSpec` class as well. And I think we should also rename all other occurrences of `rockylinux` with `rockyLinux` (CSS class names etc.) just to be consistent everywhere.
> 
> ![screenshot-localhost_8000-2022 06 14-20_41_11](https://user-images.githubusercontent.com/13975988/173619737-acb5a6b2-90fc-44b0-9489-1a2c87538b5e.png)

I have fixed this issue by changing the property is OperatingSystemSpec class.

2022-06-14 19:56 UTC, Waseem826 commented
/retest

2022-06-15 12:58 UTC, Talha-Jamil-TJ commented
/retest pre-dashboard-check-static

2022-06-15 13:01 UTC, Waseem826 commented
/retest

2022-06-15 14:28 UTC, Waseem826 approved these changes
/approve

2022-06-15 14:54 UTC, merged