Replace text inputs with number stepper for project quota dialog
kubermatic/dashboard pull request #4706
Opened 2022-07-21 09:33 UTC by Talha-Jamil-TJ

**What does this PR do / Why do we need it**:

This PR replaces `text inputs` with `number stepper inputs` for **project quota dialog**

> Before

![image](https://user-images.githubusercontent.com/56511988/180180755-f51aa806-b3b8-4530-b631-f1e85496ecb2.png)

> After
<img width="667" alt="image" src="https://user-images.githubusercontent.com/56511988/180180819-33ef2191-d8a4-4f89-953e-207b47c5596a.png">

**Which issue(s) this PR fixes** :

Fixes #4686

**Release Note**:

```release-note
NONE
```

2022-07-21 15:05 UTC, Waseem826 requested changes
Some feedback. PTAL

2022-07-21 15:05 UTC, Waseem826 commented on src/app/dynamic/enterprise/quotas/project-quota-dialog/component.ts
> +    private readonly _ref: ChangeDetectorRef,
```suggestion
    private readonly _cdr: ChangeDetectorRef,
```

2022-07-21 15:06 UTC, Waseem826 commented
We should replace other `RAM` words with `Memory`

![screenshot-localhost_8000-2022 07 21-18_31_47](https://user-images.githubusercontent.com/13975988/180247968-5b177a01-2e59-435a-8f41-866044e89510.png)

2022-07-21 15:07 UTC, Waseem826 commented
Can we just display project as a text instead of using a disabled mat-select?

![screenshot-localhost_8000-2022 07 21-18_35_51](https://user-images.githubusercontent.com/13975988/180248107-334921b0-f6ae-49a6-b70d-f6977f60a618.png)

2022-07-21 15:08 UTC, Waseem826 commented
This is not related to this PR but would be nice if we can display `-` in empty columns.

![screenshot-localhost_8000-2022 07 21-20_04_41](https://user-images.githubusercontent.com/13975988/180248314-cd09397b-584f-41c9-88bd-2b3d6a632ea8.png)

2022-07-22 09:58 UTC, Talha-Jamil-TJ commented
> This is not related to this PR but would be nice if we can display `-` in empty columns.
> 
> ![screenshot-localhost_8000-2022 07 21-20_04_41](https://user-images.githubusercontent.com/13975988/180248314-cd09397b-584f-41c9-88bd-2b3d6a632ea8.png)

Need to get it approved from @cschieder

2022-07-22 10:13 UTC, Talha-Jamil-TJ commented
> Can we just display project as a text instead of using a disabled mat-select?
> 
> ![screenshot-localhost_8000-2022 07 21-18_35_51](https://user-images.githubusercontent.com/13975988/180248107-334921b0-f6ae-49a6-b70d-f6977f60a618.png)

As there wasn't any designs for this modal, I reused the `add` dialog for `edit`, and disabling the project select was suggested by @lsviben

2022-07-22 10:27 UTC, Talha-Jamil-TJ commented on src/app/dynamic/enterprise/quotas/project-quota-dialog/component.ts
> +    private readonly _ref: ChangeDetectorRef,
feedback implemented

2022-07-22 10:28 UTC, Talha-Jamil-TJ commented on src/app/dynamic/enterprise/quotas/project-quota-dialog/component.ts
> +    // This subscription prevents "Expression changed after checked" error
feedback implemented

2022-07-22 10:28 UTC, Talha-Jamil-TJ commented on src/app/dynamic/enterprise/quotas/project-quota-dialog/component.ts
> +    // This subscription prevents "Expression changed after checked" error
@Waseem826 what about the comment  on the above subscription?

2022-07-22 10:29 UTC, Talha-Jamil-TJ commented on src/app/dynamic/enterprise/quotas/quota.ts
>  export class QuotaService implements OnDestroy {
file renamed to `service.ts`

2022-07-22 10:34 UTC, Talha-Jamil-TJ commented on src/app/shared/components/number-stepper/template.html
> +         (blur)="onTouch()"
According to angular docs this should be `blur` event.

<img width="800" alt="image" src="https://user-images.githubusercontent.com/56511988/180421447-0d0ca031-edcd-4959-853a-671cfc8f5aa6.png">

see: https://angular.io/api/forms/ControlValueAccessor

2022-07-22 11:26 UTC, Waseem826 commented on src/app/dynamic/enterprise/quotas/project-quota-dialog/component.ts
> +    // This subscription prevents "Expression changed after checked" error
We can keep that

2022-07-22 14:03 UTC, Talha-Jamil-TJ commented on src/app/dynamic/enterprise/quotas/component.ts
> +        switchMap(_ => this._quotaService.deleteQuota(name))
we don't need to manually unsubscribe to `afterClosed()` as it does it on its own

<img width="729" alt="image" src="https://user-images.githubusercontent.com/56511988/180455849-518f7c60-8c97-4246-b3df-64eef696fd92.png">

2022-07-22 14:09 UTC, Talha-Jamil-TJ commented on src/app/dynamic/enterprise/quotas/project-quota-dialog/component.ts
> +    Object.values(this.quotaGroup.controls).forEach(control => {
Yes, users can enter `0`, but it won't make the form valid, and those values won't go into the API payload.

2022-07-26 08:32 UTC, Waseem826 approved these changes
/approve

2022-07-26 08:33 UTC, merged