improvement gke cluster creation
kubermatic/dashboard pull request #4917
Opened 2022-08-31 13:11 UTC by ahmadhamzh

**What this PR does / why we need it**:
refactor the input fields and add the machine and disk types for GKE cluster creation
**Which issue(s) this PR fixes**:
Fixes #4786

**What type of PR is this?**
/kind feature

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
add the machine types and disk types fields for GKE cluster creation 
```
```documentation
NONE
```

2022-09-01 08:51 UTC, KhizerRehan commented on src/app/external-cluster-wizard/steps/external-cluster/provider/gke/component.ts
> +        .valueChanges.pipe(takeUntil(this._unsubscribe))
Try to clear disktypes and machine types when new API call is send.

Check `_clearVmSize` in AKSClusterSettingsComponent as a reference

2022-09-01 09:12 UTC, KhizerRehan requested changes
Some feedback added

2022-09-01 09:12 UTC, KhizerRehan commented on src/app/external-cluster-wizard/steps/external-cluster/provider/gke/template.html
> +        {{machineType.name+" ("+machineType.vcpus +" vCPUs "+machineType.memory+"MB RAM)"}}
**Changes should be tested on both (Wizard/MD dialog)**

Don't add computation on template instead create a method in `ts` file which can be also passed as [valueFormatter] in component. 


Show both name + computation on Selection Too

![machine-type (display-name)](https://user-images.githubusercontent.com/17727069/187875725-be650314-90c7-4ce3-8d84-af861d878e7d.png)

2022-09-01 09:12 UTC, KhizerRehan commented on src/app/external-cluster-wizard/steps/external-cluster/provider/gke/template.html
> +        {{diskType.description}}
**Changes should be tested on both (Wizard/MD dialog)**

![disk-type (display-name)](https://user-images.githubusercontent.com/17727069/187876081-0d7360e2-841e-496c-ace0-a6a136b82ce2.png)

**show as**
![showas](https://user-images.githubusercontent.com/17727069/187876313-1db421ff-363d-43f3-bde3-44f90aadb48c.png)

2022-09-01 09:12 UTC, KhizerRehan commented on src/app/external-cluster-wizard/steps/external-cluster/provider/gke/component.ts
> +    this._externalClusterService
correct  state shown based on API calls see method `_getGKEMachineTypesForMachineDeployment`
set value before API call
this.<LabelName> = <Type>.Loading;

2022-09-01 09:13 UTC, KhizerRehan commented on src/app/external-cluster-wizard/steps/external-cluster/provider/gke/component.ts
> +        diskTypes.map(diskType => {
Check this comment: https://github.com/kubermatic/dashboard/pull/4917#discussion_r960396002

2022-09-01 09:13 UTC, KhizerRehan requested changes

2022-09-01 09:13 UTC, KhizerRehan commented on src/app/external-cluster-wizard/steps/external-cluster/provider/gke/component.ts
> +        machineTypes.map(machineType => {
Check this comment: https://github.com/kubermatic/dashboard/pull/4917#discussion_r960396002

2022-09-01 09:13 UTC, KhizerRehan commented on src/app/external-cluster-wizard/steps/external-cluster/provider/gke/component.ts
> +        machineTypes.map(machineType => {
Check this comment: https://github.com/kubermatic/dashboard/pull/4917#discussion_r960396002

2022-09-02 04:39 UTC, ahmadhamzh commented on src/app/external-cluster-wizard/steps/external-cluster/provider/gke/component.ts
> +          if (diskType.name === this.DISK_TYPE_DEFAULT_VALUE) {
can we use `includes` here ?? `diskTypes` is an array of objects and `this.DEFAULT_LOCATION` is a string

2022-09-05 12:52 UTC, KhizerRehan commented
@ahmadhamzh please test also
- once you select go to details step
- go back change preset 
- select another valid preset `next` button is still `disabled` currently. It should be enabled

2022-09-06 15:50 UTC, KhizerRehan commented
/test pre-dashboard-build-image

2022-09-06 16:52 UTC, ahmadhamzh commented
/retest

2022-09-06 17:28 UTC, ahmadhamzh commented
/lgtm

2022-09-07 08:04 UTC, ahmadhamzh commented
/retest

2022-09-07 08:29 UTC, KhizerRehan commented
/lgtm

2022-09-07 08:29 UTC, merged