[WIP] Add prow job for running api unit tests
kubermatic/dashboard pull request #5175
Opened 2022-10-31 14:50 UTC by pkprzekwas

**What this PR does / why we need it**:
As we moved API code to this repository we need to copy appropriate prow pipelines to validate and test the code.

**Which issue(s) this PR fixes**:
Fixes #5116 

**What type of PR is this?**
/kind chore

**Does this PR introduce a user-facing change? Then add your Release Note here**:
```release-note
NONE
```

**Documentation**:
```documentation
NONE
```

2022-11-02 15:28 UTC, lsviben commented
/approve

2022-11-03 08:12 UTC, ahmedwaleedmalik requested changes

2022-11-03 08:12 UTC, ahmedwaleedmalik commented on .golangci.apis.yml
> +# Copyright 2022 The Kubermatic Kubernetes Platform contributors.
We don't need this.

2022-11-03 08:12 UTC, ahmedwaleedmalik commented on .gimps.yaml
> +# Copyright 2021 The Kubermatic Kubernetes Platform contributors.
```suggestion
# Copyright 2022 The Kubermatic Kubernetes Platform contributors.
```

2022-11-03 08:12 UTC, ahmedwaleedmalik commented on .prow/api.yaml
> +        - image: quay.io/kubermatic/build:go-1.19-node-18-2
We recently updated to Go 1.19.3 for the KKP API so you'll have to switch these CI jobs to `quay.io/kubermatic/build:go-1.19-node-18-4`

2022-11-03 10:38 UTC, pkprzekwas commented on .golangci.apis.yml
> +# Copyright 2022 The Kubermatic Kubernetes Platform contributors.
Oh, good catch. It's CRD only, right?

2022-11-03 11:19 UTC, pkprzekwas commented
/retest pre-dashboard-api-e2e

2022-11-03 11:21 UTC, pkprzekwas commented
/test pre-dashboard-api-e2e

2022-11-03 11:47 UTC, ahmedwaleedmalik commented on .golangci.apis.yml
> +# Copyright 2022 The Kubermatic Kubernetes Platform contributors.
Yup that's correct.

2022-11-03 11:49 UTC, ahmedwaleedmalik commented
> pre-dashboard-test-full-e2e-ce

`cat: hack/ci/testdata/oauth_values.yaml: No such file or directory

2022-11-03 13:51 UTC, pkprzekwas commented
> We can ignore pre-dashboard-test-e2e and pre-dashboard-test-e2e-ce but might need a fix for the following
> 
> > pre-dashboard-test-full-e2e-ce pre-dashboard-test-full-e2e-ce
> 
> `cat: hack/ci/testdata/oauth_values.yaml: No such file or directory`

Failing test seems to be a result of https://github.com/kubermatic/kubermatic/pull/11258/files

2022-11-03 14:13 UTC, ahmedwaleedmalik approved these changes
/approve 🚀

2022-11-04 07:20 UTC, ahmedwaleedmalik commented
Closed and reopened the PR since it was stuck in the merge pool.

2022-11-04 07:54 UTC, merged