Added logic disable "Enable Kubernetes Dashboard" checkbox
kubermatic/dashboard pull request #5250
Opened 2022-11-11 11:58 UTC by Talha-Jamil-TJ

**What this PR does / why we need it**:
Logic to disable the `Enable Kubernetes Dashboard` checkbox in the admin setting page based on `OIDCKubeCfgEndpoint` and `OpenIDAuthPlugin` feature gates 

**Which issue(s) this PR fixes**:

Fixes #5220

**What type of PR is this?**
/kind feature

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
In the interface section of admin settings, Enable Kubernetes Dashboard checkbox will be disabled when either OIDCKubeCfgEndpoint or OpenIDAuthPlugin feature flags are disabled
```

**Documentation**:

```documentation
NONE
```

2022-11-11 14:51 UTC, Waseem826 requested changes
@Talha-Jamil-TJ E2E tests are broken due to changes in this PR. PTAL

2022-11-11 14:52 UTC, Waseem826 commented on src/app/settings/admin/interface/template.html
> +            <ng-container *ngIf="!isOpenIDAuthPluginEnabled">openIDAuthPlugin</ng-container>
Should we wrap `konnectivityService` and `openIDAuthPlugin` inside `code` block?

2022-11-12 08:35 UTC, ahmedwaleedmalik commented
/hold
Temporary

2022-11-13 06:39 UTC, ahmedwaleedmalik commented
/unhold

2022-11-16 08:20 UTC, KhizerRehan commented on modules/web/src/app/settings/admin/interface/template.html
> +              <a href="https://docs.kubermatic.com/kubermatic/main/tutorials-howtos/oidc-provider-configuration/share-clusters-via-delegated-oidc-authentication/"
FYI i have linked the same link and docs has something related to following Feature gates as per discussion with patryk docs will be extended for same url.

![Uploading configuration.png…]()

2022-11-16 08:20 UTC, KhizerRehan commented on modules/web/src/app/settings/admin/interface/template.html
> +              <a href="https://docs.kubermatic.com/kubermatic/main/tutorials-howtos/oidc-provider-configuration/share-clusters-via-delegated-oidc-authentication/"
FYI i have linked the same link and docs has something related to following Feature gates as per discussion with patryk docs will be extended for same url.

<img width="748" alt="configuration" src="https://user-images.githubusercontent.com/17727069/202126282-7f8ebd56-504f-46f6-99c4-fff21cd69eac.png">

2022-11-16 08:59 UTC, Waseem826 requested changes
Couple of comments. PTAL

2022-11-16 08:59 UTC, Waseem826 commented on modules/web/src/app/settings/admin/interface/template.html
> +            <mat-hint *ngIf="!isOIDCKubeCfgEndpointEnabled">This feature is disabled. Visit the
I think we should also show some hint when `isOpenIDAuthPluginEnabled` is `false` or can it be the same hint in both cases?

2022-11-16 08:59 UTC, Waseem826 commented on modules/web/src/app/settings/admin/interface/component.ts
> +  onUpdateEnableKubernetesDashboard() {
```suggestion
  verifyEnableKubernetesDashboardRequirements() {
```

2022-11-16 10:12 UTC, Waseem826 approved these changes
/approve

2022-11-16 10:29 UTC, merged