Modify Project Overview
kubermatic/dashboard pull request #5455
Opened 2022-12-21 08:59 UTC by ahmadhamzh

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #5323

**What type of PR is this?**
/kind design

```release-note
NONE
```
```documentation
NONE
```

2022-12-21 10:35 UTC, ahmadhamzh commented
![Screenshot from 2022-12-21 13-33-02](https://user-images.githubusercontent.com/85109141/208884787-b807404a-8aaa-409f-9529-f5e293f74703.png)

![Screenshot from 2022-12-21 13-30-12](https://user-images.githubusercontent.com/85109141/208884866-3d11996c-5281-4199-86db-8fa466b5b4ca.png)

2022-12-21 10:55 UTC, Waseem826 requested changes
Some feedback. PTAL

2022-12-21 10:55 UTC, Waseem826 commented on modules/web/src/app/project-overview/members-overview/template.html
>                (click)="membersAndGroupsNavigate()">
We should also rename this method
```suggestion
              (click)="navigateToMembers()">
```

2022-12-21 10:55 UTC, Waseem826 commented on modules/web/src/app/project-overview/template.html
> +            <km-labels oneLineLimit=true
```suggestion
            <km-labels [oneLineLimit]="true"
```

2022-12-21 10:55 UTC, Waseem826 commented on modules/web/src/app/shared/components/labels/component.ts
> +  get showLabelsText(): string {
I think we can handle this directly inside HTML instead of adding this getter. Wdyt?

2022-12-21 10:55 UTC, Waseem826 commented on modules/web/src/app/shared/components/labels/component.ts
> +  showAndHideAllLabels(): void {
```suggestion
  toggleHiddenLabels(): void {
```

2022-12-21 10:55 UTC, Waseem826 commented on modules/web/src/app/shared/components/labels/component.ts
> +    if (document.getElementById('km-labels').offsetHeight > labelsElem) {
You should inject `private readonly _elRef:ElementRef` in `constructor` and then do this:
```suggestion
    if (this._elRef.nativeElement.offsetHeight > labelsElem) {
```

If this doesn't work then please use `@ViewChild` for getting reference of `div`.

2022-12-21 10:55 UTC, Waseem826 commented on modules/web/src/app/shared/components/labels/component.ts
> +    this.oneLineLimit && this._checkLabelsHeight();
`ngAfterViewInit` will run after `ngOnInit` so I think we can remove this line here and keep it in `ngAfterViewInit`.

2022-12-21 10:55 UTC, Waseem826 commented on modules/web/src/app/shared/components/labels/component.ts
> +  showAndHideExtraLabels = false;
```suggestion
  hideExtraLabels = false;
```

2022-12-21 10:55 UTC, Waseem826 commented on modules/web/src/app/shared/components/labels/template.html
> +<div id="km-labels"
```suggestion
<div id="labels-container"
```

2022-12-21 16:16 UTC, ahmadhamzh commented
/retest

2022-12-22 08:58 UTC, Waseem826 requested changes
Few suggestions. PTAL

2022-12-22 08:58 UTC, Waseem826 commented on modules/web/src/app/shared/components/labels/style.scss
> +  width: 120px;
```suggestion
  min-width: 120px;
```
So that the text doesn't break on small screen resolution.

2022-12-22 08:58 UTC, Waseem826 commented on modules/web/src/app/shared/components/labels/template.html
> +  <mat-chip-list [ngClass]="{'hide-extra-labels': showHiddenLabels && oneLineLimit}"
```suggestion
  <mat-chip-list [ngClass]="{'hide-extra-labels': oneLineLimit && !showHiddenLabels}"
```
`showHiddenLabels` condition is flipped for better readability.

2022-12-22 08:58 UTC, Waseem826 commented on modules/web/src/app/shared/components/labels/template.html
> +    <i class="km-icon-mask km-icon-arrow-{{showHiddenLabels ? 'down' : 'up'}}"></i>
```suggestion
       (click)="toggleHiddenLabels()">{{showHiddenLabels ? 'HIDE ALL' : 'SHOW ALL'}}
    <i class="km-icon-mask km-icon-arrow-{{showHiddenLabels ? 'up' : 'down'}}"></i>
```

2022-12-22 12:56 UTC, Waseem826 approved these changes
/approve

2022-12-22 13:07 UTC, ahmadhamzh commented
/retest

2022-12-22 13:18 UTC, merged