fix the handleProviderChange methode
kubermatic/dashboard pull request #5544
Opened 2023-01-16 12:00 UTC by ahmadhamzh

**What this PR does / why we need it**
fix displaying steps for wizard in case change provider after choosing kubeadm provider

**Which issue(s) this PR fixes**:
Fixes #5505 

**What type of PR is this?**
/kind bug

```release-note
NONE
```

```documentation
NONE
```

2023-01-16 15:38 UTC, ahmadhamzh commented
/retest

2023-01-16 18:35 UTC, ahmadhamzh commented
/retest

2023-01-17 10:29 UTC, Waseem826 requested changes
Some feedback. PTAL

2023-01-17 10:29 UTC, Waseem826 commented on modules/web/src/app/core/services/wizard/wizard.ts
> +      this._parent._steps = steps;
We should call the setter method instead.
```suggestion
      this._parent.steps = steps;
```

2023-01-17 10:29 UTC, Waseem826 commented on modules/web/src/app/core/services/wizard/wizard.ts
> +  getStepsForEditClusterTemplate(provider: NodeProvider) {
Wdyt?
```suggestion
  forceHandleProviderChange(provider: NodeProvider) {
```

2023-01-18 08:10 UTC, ahmadhamzh commented on modules/web/src/app/core/services/wizard/wizard.ts
> +  getStepsForEditClusterTemplate(provider: NodeProvider) {
sounds better

2023-01-18 08:31 UTC, Waseem826 approved these changes
/approve

2023-01-18 08:32 UTC, merged