Add functionality to edit initial values of Cilium application
kubermatic/dashboard pull request #5579
Opened 2023-01-20 11:26 UTC by Waseem826

**What this PR does / why we need it**:
Add functionality to edit initial values of Cilium application when `Cilium` plugin is selected for cluster.

**Cluster Step:**

![screenshot-localhost_8000-2023 01 20-16_16_36](https://user-images.githubusercontent.com/13975988/213683789-dcd74ab3-0567-4231-892b-d464c6f087cf.png)

**Dialog:**

![screenshot-localhost_8000-2023 01 20-16_17_00](https://user-images.githubusercontent.com/13975988/213683885-4705a8f9-56aa-4b35-bcd9-b4569d20c9d3.png)

**Which issue(s) this PR fixes**:

Fixes #5524 

**What type of PR is this?**

/kind feature

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Add functionality to edit initial values of Cilium application when Cilium plugin is selected.
```

**Documentation**:

```documentation
NONE
```

2023-01-20 11:42 UTC, Waseem826 commented
/retest

2023-01-20 11:56 UTC, Waseem826 commented
/hold
I need to update annotation value format in request payload.

2023-01-20 14:05 UTC, KhizerRehan requested changes
Feedback

2023-01-20 14:07 UTC, KhizerRehan commented
Otherwise changes looks good 👍🏽 
/approve
/lgtm

2023-01-24 09:55 UTC, Waseem826 commented on modules/web/src/app/wizard/step/cluster/component.ts
> +    this.canEditCNIValues = cniPlugin === CNIPlugin.Cilium && cniVersion && gte(coerce(cniVersion), '1.13.0');
I didn't create a class property because this component already had too many of them. But I've added one now for consistency purpose.

2023-01-24 10:34 UTC, Waseem826 commented
/unhold

2023-01-24 11:27 UTC, ahmedwaleedmalik approved these changes
/approve

2023-01-24 11:28 UTC, merged