[release/v2.23] Patch release version bump, KKP update
kubermatic/dashboard pull request #6278
Opened 2023-10-13 09:22 UTC by pkprzekwas

**What this PR does / why we need it**:
What the title says.

**What type of PR is this?**
/kind chore

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```

2023-10-13 09:30 UTC, embik requested changes

2023-10-13 10:02 UTC, pkprzekwas commented on modules/api/go.mod
> +	k8c.io/kubermatic/v2 v2.23.5-0.20231013074658-4f07772499c4
Good point. Totally forgot about it.

2023-10-13 10:04 UTC, pkprzekwas commented on modules/web/src/assets/config/changelog.json
> +      "description": "Introduce `DisableAdminKubeconfig` flag in `KubermaticSettings` to disable the admin kubeconfig feature from dashboard."
AFAIK there is a switch in the dashboard.

2023-10-13 10:58 UTC, pkprzekwas commented
/test pre-dashboard-api-unit

2023-10-13 12:28 UTC, Waseem826 approved these changes
/approve

2023-10-13 12:59 UTC, pkprzekwas commented
/hold

2023-10-16 09:10 UTC, pkprzekwas commented
/test pre-dashboard-api-unit

2023-10-16 11:31 UTC, pkprzekwas commented
/test pre-dashboard-web-integration-tests

2023-10-16 11:55 UTC, pkprzekwas commented
/hold cancel

2023-10-16 11:57 UTC, Waseem826 approved these changes

2023-10-16 13:11 UTC, ahmedwaleedmalik approved these changes
/approve

2023-10-16 13:56 UTC, embik commented
/retest

2023-10-16 14:30 UTC, embik commented
/retest

2023-10-16 14:58 UTC, merged