Bump version changes for KKP Apr 2024 patch release
kubermatic/dashboard pull request #6652
Opened 2024-04-15 10:56 UTC by archups

**What this PR does / why we need it**:
This PR is for bumping the version changes for KKP Apr 2024 patch release 2.25.1.

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**
/kind documentation
/kind chore

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```

2024-04-16 12:22 UTC, embik requested changes

2024-04-16 12:22 UTC, embik commented on modules/web/src/assets/config/changelog.json
>    "entries": [
This should probably also have:

- Cluster-autoscaler addon now works based on the namespace instead of cluster names; all MachineDeployments in the `kube-system` namespace are scaled ([#13202](https://github.com/kubermatic/kubermatic/pull/13202))
- Add Canal CNI version v3.27.3, having a fix to the ipset incompatibility bug ([#13245](https://github.com/kubermatic/kubermatic/pull/13245))
- Update Cilium to 1.14.9 and 1.13.14, mitigating CVE-2024-28860 and CVE-2024-28248 ([#13242](https://github.com/kubermatic/kubermatic/pull/13242))

The cluster-autoscaler entry is very technical, I'd just list that as "Fix regression preventing cluster-autoscaler addon from properly scaling clusters".

2024-04-17 04:36 UTC, archups commented on modules/web/src/assets/config/changelog.json
>    "entries": [
done!

2024-04-17 06:22 UTC, embik commented on modules/web/src/assets/config/changelog.json
> +      "description": "Update Cilium to 1.14.9 and 1.13.14, mitigating [CVE-2024-28860](https://github.com/advisories/GHSA-pwqm-x5x6-5586) and [CVE-2024-28248](https://github.com/advisories/GHSA-68mj-
I don't think this supports markdown (note to myself: remove the links).

2024-04-17 06:36 UTC, archups commented on modules/web/src/assets/config/changelog.json
> +      "description": "Update Cilium to 1.14.9 and 1.13.14, mitigating [CVE-2024-28860](https://github.com/advisories/GHSA-pwqm-x5x6-5586) and [CVE-2024-28248](https://github.com/advisories/GHSA-68mj-
Fixed!

2024-04-18 09:23 UTC, embik approved these changes

2024-04-18 09:27 UTC, Waseem826 approved these changes
/approve

2024-04-18 09:29 UTC, merged